---
services:
  redmine:
    user: redmine
    image: redmine:4.2.1
    configs:
      - source: saml
        target: /usr/src/redmine/config/initializers/saml.rb
        mode: 0644
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
    volumes:
      - ./redmine/plugins:/usr/src/redmine/plugins

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine

configs:
  saml:
    file: ./redmine/config/initializers/saml.rb
